---
title: "Practical_One"
date:  2024-02-08
format: html
editor: visual
---

## Libraries

```{r, include=FALSE}
#| label: setup
#| include: false
library(readr)
library(gamlss)
```

## Question 1

```{r, include=FALSE}
#| label: checking rows with NA and printing the rows
#| echo: false
airquality
data_na <- is.na(airquality)
row_i <- rowSums(data_na)
r_na <- airquality[row_i> 0,]
print(r_na)
```

## Question 2

```{r}
#| label: Calculating mean, standard deviation, minimun value and maximum value for each level of Ozone level and Temperature
#| echo: false
Col_Ozone <- airquality$Ozone
Col_Temp <- airquality$Temp

#Calculating the means
Ozone_mean <- mean(Col_Ozone, na.rm = TRUE)
Temp_mean <- mean(Col_Temp, na.rm =  TRUE)

#Calculating the standard deviations
Ozone_sd <- sd(Col_Ozone, na.rm = TRUE)
Temp_sd <- sd(Col_Temp, na.rm =  TRUE)

#Minimum values
Ozone_min <- as.numeric(min(na.omit(Col_Ozone)))
Temp_min <- as.numeric(min(na.omit(Col_Temp)))

#Maximum values
Ozone_max <- as.numeric(max(na.omit(Col_Ozone)))
Temp_max <- as.numeric(max(na.omit(Col_Temp)))
```

## Question 3

```{r}
#| label: Fitting a linear regression model using the design matrix

data(cars)
head(cars)
X <- cbind(1, cars$speed)
y <- cars$dist

beta <- solve(t(X)%*%X)%*%t(X)%*%y
beta
```

## Question 4

```{r}
#| label: Fitting a linear regression model using R
#| echo: false

m1 <- lm(dist ~ speed, data = cars)
summary(m1)
```
